# Generated by Django 2.2.28 on 2023-11-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalerie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='race',
            new_name='sexe',
        ),
    ]
